# configs/dataset.yaml
root: ./data
images_dir: images
masks_dir: masks
classes:             
  - rule_00_arrow_not_touching
  - rule_01_text_overlap_line
  - rule_02_missing_dimension
C: 3                  
tile_size: 1024
tile_overlap: 256
num_workers: 4
seed: 42
folds: 1              
min_positive_area: 64 
