# configs/infer.yaml
tta: [hflip, vflip]         # optional
merge: mean                 # mean | gmean | max
tile_size: 1024
tile_overlap: 256
min_component_area:         # optional per-class small blob removal
  - 32
  - 32
  - 32
thresholds_file: configs/thresholds.json
