# configs/train.yaml
epochs: 40
batch_size: 4
optimizer: adamw
lr: 3.0e-4
weight_decay: 1.0e-4
sched: onecycle          # onecycle | cosine | reduce_on_plateau
amp: true
grad_clip: 1.0
freeze_encoder_stages: [0, 1]  # warmup freeze (stem + stage1)
unfreeze_at_epoch: 2
loss: dice_bce           # dice_bce | dice_focal | tversky | dice_ce
focal_gamma: 2.0
tversky_alpha: 0.7
tversky_beta: 0.3
class_weights: null      # e.g., [1.0, 1.4, 1.8] (inverse sqrt freq)
save_metric: macro_mIoU  # checkpoint by this metric
early_stop_patience: 8
